<?php
//
////$numbers = array(1,2,4,4,5,5);
////print_r($numbers[0]);
////echo $numbers[3];
////$ages =array('haz' => 'ds',
////            'moh' => 'sd',
////            'zoh' => 'mk',);
////print_r($ages);
////echo "<br>";
////echo $ages['zoh'];
////echo count($ages);
////echo "<br>";
////foreach ($ages as $name => $age){
////
////    echo 'the name is '.$name." and the age is $age";
////}
////function sumNum($x,$y){
////    return $x + $y;
////}
//class User{
//    private $id;
//    private $username;
//    protected $email  ;
//    private $password;
//
//    public function __construct($username , $password){
//        $this->username = $username;
//        $this->password = $password;
//        echo 'Constructor Called';
//        echo '<br>';
//    }
//    public function register(){
//        echo $this->username.' is Registerd';
//    }
//    public function login($username , $password){
//        echo $username.''.$password;
//        $this->auth_user($username,$password);
//
//    }
//    public function  auth_user($username,$password){
//        echo '<br>';
//        echo $username.' is authnticatd';
//
//    }
//    public function setUserName($username){
//        $this->username = $username;
//    }
//    public function getUserName(){
//        return $this->username;
//    }
//    public function __destruct(){
//        echo '<br>';
//
//        echo 'destructor is called';
//    }
//
//}
//class Admin extends User{
//    public $role;
//    public function setEmail($email){
//        $this->email = $email;
//        return $this->email;
//    }
//    public function getEmail(){
//        echo '<br>';
//        echo $this->email;
//    }
//}
//class Product{
//    public static $maxProductStorage =100;
//    public static function validatePorduct($storage){
//        // scope resolution operator
//        if($storage <= self::$maxProductStorage ){
//            return true;
//        }else{
//            return false;
//        }
//    }
//}
//abstract  class Animal{
//    public $name;
//    public $color;
//    public function describe(){
//        return$this->name.' is '.$this->color;
//    }
//    abstract public function makesound();
//}
//class Duck extends Animal {
//    public function describe()
//    {
//        return parent::describe(); // TODO: Change the autogenerated stub
//    }
//    public function makesound()
//    {
//        return 'Quack Quack';
//    }
//}
//class Dog extends Animal {
//    public function describe()
//    {
//        return parent::describe(); // TODO: Change the autogenerated stub
//    }
//    public function makesound()
//    {
//        return 'Woaf Woaf';
//    }
//}

//$user = new User('morad','password');
//
//$user->register();
//echo '<br>';
//$user->login('hazem','123456');
//echo '<br>';
//echo '<br>';
//$user->setUserName('ahmed');
//echo $user->getUserName();
//echo '<br>';
//$admin = new Admin('Jhon Dow','12er34');
//$admin->register();
//$admin->setEmail('admin@gmail.com');
//$admin->getEmail();
//
//$storageQuantity = 101;
//if (Product::validatePorduct($storageQuantity)){
//    echo 'Quantity is acceptable';
//}else{
//    echo 'Quantity is not acceptable';
//}
//$dog = new Dog();
//$dog->name = 'rex';
//$dog->color = 'black';
//echo $dog->describe();
//echo '<br>';
//echo $dog->makesound();
//include 'Foo.php';
//include 'Bar.php';
//$foo = new Foo();
//$bar = new Bar();
//$foo->sayHello();
